app/admin/routes.py
from flask import Blueprint, current_app, render_template, request
from flask_login import login_required

from app.common.decorators import check_confirmed
from app.auth.models import User
from app.post.models import Post
from .decorators import admin_required

bp = Blueprint('admin', __name__, template_folder='templates')

@bp.route('/admin')
@login_required
@check_confirmed
@admin_required
def admin():
    return render_template('admin.html')

@bp.route('/admin/users')
@login_required
@check_confirmed
@admin_required
def show_users():
    page = request.args.get('page', 1, type=int)
    users = User.query.paginate(page, current_app.config['USER_PER_PAGE'])
    return render_template('show_users.html', users=users)

@bp.route('/admin/posts')
@login_required
@check_confirmed
@admin_required
def show_posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.paginate(page, current_app.config['POST_PER_PAGE'])
    return render_template('show_posts.html', posts=posts)

app/admin/templates/_base_admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Welcome to Admin Dashboard</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>

<body>

    <header
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom p-3 bg-dark text-white">
        <a href="{{ url_for('admin.admin') }}"
            class="h3 d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            MiniBlog Admin
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{{ url_for('public.index') }}" class="nav-link px-2 text-white">View Site</a>


            <li><a href="{{ url_for('dashboard.dashboard') }}" class="nav-link px-2 text-white">Dashboard</a></li>
        </ul>

        <div class="col-md-3 text-end">
            <a href="{{ url_for('auth.logout') }}" class="btn btn-warning">Logout</a>
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
</body>

</html>

app/admin/templates/admin.html
{% extends '_base_admin.html' %}

{% block title %}{{ current_user.username }}{% endblock %}

{% block content %}

<div style="width: 100%; max-width: 500px;" class="py-5 my-5">
    <p class="h2">Sitio de administración</p>
    <ul class="list-group">
        <li class="list-group-item p-3">
            <a href="{{url_for('admin.show_users')}}" class="h3">Administrar usuarios</a>
        </li>
        <li class="list-group-item  p-3">
            <a href="{{url_for('admin.show_posts')}}" class="h3">Administrar artículos</a>
        </li>
    </ul>
</div>

{% endblock %}

app/admin/templates/show_posts.html
{% extends '_base_admin.html' %}

{% block title %}{{ current_user.username }}{% endblock %}

{% block content %}

<main class="mb-5 pb-5">

    <div class="d-flex mt-3 justify-content-between">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('admin.admin') }}">Admin</a></li>
                <li class="breadcrumb-item active" aria-current="page">Publicaciones</li>
            </ol>
        </nav>
        <div>
            <p class="h4">Welcome {{ current_user }}</p>
        </div>
    </div>

    <h4 class="my-2 py-2">Publicaciones registradas: {{ posts.total }}</h4>

    <table class="table table-striped mb-5">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Autor</th>
                <th>Comentarios</th>
                <th>Likes</th>
                <th>Tiempo de lectura</th>
                <th>Creado</th>
                <th>Modificado</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
            {% for post in posts.items %}
            <tr>
                <td><a href="{{url_for('post.show_post', uuid=post.public_id, slug=post.title_slug)}}">{{ post.title
                        }}</a>
                </td>
                <td><a href="{{url_for('public.show_user', username=post.author.username )}}">{{ post.author.username
                        }}</a></td>
                <td>{{ post.comments.__len__() }}</td>
                <td>{{ post.likes.count() }}</td>
                <td>{{ post.read_time }} min</td>
                <td>{{ post.created|strftime }}</td>
                <td>{{ post.updated|strftime }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% from '_paginationhelper.html' import render_pagination %}

    {{ render_pagination(posts, 'admin.show_posts') }}
</main>


{% endblock %}

app/admin/templates/show_users.html
{% extends '_base_admin.html' %}

{% block title %}{{ current_user.username }}{% endblock %}

{% block content %}

<main class="mb-5 pb-5">
    <div class="d-flex mt-3 justify-content-between">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('admin.admin') }}">Admin</a></li>
                <li class="breadcrumb-item active" aria-current="page">Users</li>
            </ol>
        </nav>
        <div>
            <p class="h4">Welcome {{ current_user }}</p>
        </div>
    </div>
    
    <h4 class="my-2 py-2">Usuarios registrados: {{ users.total }}</h4>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Followers</th>
                <th>Following</th>
                <th>Post</th>
                <th>Registrado</th>
                <th>Admin</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users.items %}
            <tr>
                <td><a href="{{ url_for('public.show_user', username=user.username ) }}">{{ user.username}}</a></td>
                <td>{{ user.email}}</td>
                <td>{{ user.followers.count() }}</td>
                <td>{{ user.followed.count() }}</td>
                <td>{{ user.posts.__len__() }}</td>
                <td>{{ user.created|strftime }}</td>
                <td>{{ user.admin}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    {% from '_paginationhelper.html' import render_pagination %}
    
    {{ render_pagination(users, 'admin.show_users') }}

</main>

{% endblock %}