app/post/models.py
from datetime import datetime
from uuid import uuid4

from slugify import slugify

from app.ext import db

class Post(db.Model):
    __tablename__ = 'post'
    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.String, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    title = db.Column(db.String)
    title_slug = db.Column(db.String)
    content = db.Column(db.Text)
    read_time = db.Column(db.Integer)
    comments = db.relationship('Comment',
        backref='post', lazy=True, cascade='all, delete-orphan',
        order_by='desc(Comment.id)')
    likes = db.relationship('PostLike', backref='post', lazy='dynamic')
    created = db.Column(db.DateTime, default=datetime.now())
    updated = db.Column(db.DateTime, nullable=True)

    def __init__(self, title, content, read_time, author_id):
        self.title = title
        self.content = content
        self.read_time = read_time
        self.author_id = author_id

    def __str__(self):
        return f'{self.title}'

    def save(self):
        self.title_slug = slugify(self.title)

        if not self.id:
            self.public_id = str(uuid4())
            db.session.add(self)
        else:
            self.updated = datetime.now()

        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

class PostLike(db.Model):
    __tablename__ = 'post_like'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

class Comment(db.Model):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.String, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete='CASCADE'), nullable=False)
    content = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    updated = db.Column(db.DateTime, nullable=True)

    def __init__(self, content, user_id, post_id):
        self.content = content
        self.user_id = user_id
        self.post_id = post_id

    def save(self):
        if not self.id:
            self.public_id = str(uuid4())
            db.session.add(self)
        else:
            self.updated = datetime.now()

        db.session.commit()

app/post/routes.py
from flask import Blueprint, current_app, redirect, \
                render_template, request, url_for
from flask_login import current_user, login_required

from app.common.decorators import check_confirmed
from .form import CommentForm
from .models import Comment
from .models import Post

bp = Blueprint('post', __name__, template_folder='templates')

@bp.route('/article/<string:uuid>/<string:slug>', methods=['GET', 'POST'])
def show_post(uuid, slug):
    post = Post.query.filter_by(public_id=uuid, title_slug=slug).first_or_404()
    form = CommentForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            comment = Comment(
                form.content.data,
                current_user.id,
                post.id
            )

            comment.save()
        return redirect(url_for('post.show_post',
            uuid=post.public_id,
            slug=post.title_slug
        ))
    return render_template('show_post.html', form=form, post=post)

@bp.route('/article/all')
def show_posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.id.desc()).paginate(page, current_app.config['POST_PER_PAGE'])
    return render_template('show_all_posts.html', posts=posts)

@bp.route('/like/<uuid>/<action>', methods=['GET'])
@login_required
@check_confirmed
def like_action(uuid, action):
    post = Post.query.filter_by(public_id=uuid).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        current_user.save()
    if action == 'unlike':
        current_user.unlike_post(post)
        current_user.save()
    return redirect(request.referrer)

app/post/templates/show_all_posts.html
{% extends '_base.html' %}

{% block title %}Publicaciones{% endblock %}

{% block content %}
<div class="mt-3">
    {% if posts.total != 0 %}
    <p class="h5"></p>
    <ul class="list-group list-group-flush">
        {% for post in posts.items %}
        <li class="list-group-item">
            <div>
                <h3><a href="{{ url_for('post.show_post', uuid=post.public_id, slug=post.title_slug)}}">{{
                        post.title }}</a></h3>
                <p>Escrito por <a
                        href="{{ url_for('public.show_user', username=post.author.username) }}">{{post.author.username
                        }}</a></p>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p class="h5">No se encontraron resultados</p>
    {% endif %}
</div>

{% from '_paginationhelper.html' import render_pagination %}

{{ render_pagination(posts, 'post.show_posts') }}
{% endblock %}

app/post/templates/show_post.html
{% extends '_base.html' %}

{% block title %}{{post.title}}{% endblock %}

{% block prism %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/prism.css')}}">
<script src="{{ url_for('static', filename='js/prism.js') }}"></script>
{% endblock %}

{% block content %}

<main>
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic">{{ post.title }}</h1>
        </div>
    </div>

    <div class="row g-5">
        <div class="col-md-8">
            <div>
                {{post.content|safe}}
            </div>

            <div class="card mt-5">
                <div class="card-body">
                    <h5 class="card-title">{{ post.likes.count() }} like</h5>
                    {% if current_user.is_authenticated and current_user.confirmed %}
                    <p class="card-text">Apoya a {{ post.author.username }} con tu like
                        {% if current_user.has_liked_post(post) %}
                        <a href="{{ url_for('post.like_action', uuid=post.public_id, action='unlike') }}">Unlike</a>


                        {% else %}

                        <a href="{{ url_for('post.like_action', uuid=post.public_id, action='like') }}">Like</a>
                    </p>
                        {% endif %}
                    {% else %}
                    <p class="card-text">Recuerda iniciar sección y comfirmar tu email para dar like</p>
                    {% endif %}
                </div>
            </div>


            <div class="mt-3 p-3">
                {% if post.comments != [] %}
                <p class="h3 mb-3">{{ post.comments|pluralize('Comentario') }}:</p>
                <div>
                    {% for comment in post.comments%}
                    <div class="border-bottom mb-3">
                        <p class="h5"><a
                                href="{{ url_for('public.show_user', username=comment.author.username) }}">{{comment.author.username}}</a>
                        </p>
                        <p>{{ comment.content }}</p>
                        <p>El {{ comment.created|strftime }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p class="h3 mb-3">Sin comentarios se el primero en comentar.</p>
                {% endif%}
            </div>

            <div class="my-3 pt-3">
                {% if current_user.is_authenticated and current_user.confirmed %}
                <form method="post">
                    {{ form.csrf_token() }}

                    <div class="input-group">
                        {{ form.content(class="form-control") }}
                        <button class="input-group-text">Send</button>
                    </div>
                </form>
                {% else %}
                <p class="h3">Recuerda iniciar sección y confirmar tu email para comentar</p>
                {% endif %}
            </div>
        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4 class="fst-italic">About</h4>
                    <div class="mb-0">
                        <p>Escrito por: <a href="{{ url_for('public.show_user', username=post.author.username)}}">{{
                                post.author.username }}.</a>
                        </p>

                        <p>Publicación: {{ post.created|strftime('full') }}.</p>

                        {% if post.updated %}
                        <p>Ultima edición: {{ post.updated|strftime('full') }}.</p>
                        {% endif %}

                        <p>Lectura {{ post.read_time}} minuto.</p>
                    </div>
                </div>

                <div class="p-4">
                    <h4 class="fst-italic">Mas publicaciones de {{ post.author }}</h4>
                    <ol class="list-unstyled mb-0">
                        {% for post in post.author.posts[0:15] %}
                        <li><a href="{{ url_for('post.show_post', uuid=post.public_id, slug=post.title_slug) }}">{{
                                post.title }}.</a></li>
                        {% endfor %}
                    </ol>
                </div>

            </div>
        </div>
    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">MiniBlog developed by <a href="http://github.com/NSMichelJ" target="_blank"
                rel="noopener noreferrer">NSMichelJ</a></span>
    </div>
</footer>

{% endblock %}