app/dashboard/forms.py
from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from wtforms import StringField, IntegerField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length, \
                NumberRange, Optional

from app.common.form import BaseUserForm
from app.common.form.form_validators import Password

class WritePostForm(FlaskForm):
    title = StringField('Title', validators=[
        DataRequired()
    ])
    content = CKEditorField('Content', validators=[
        DataRequired()
    ])
    read_time = IntegerField('Read time', default=1, validators=[
        NumberRange(min=1)
    ])

class EditProfileForm(BaseUserForm):
    password = PasswordField('Password', validators=[
        Optional(),
        Password(),
        Length(min=8, max=20)
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        EqualTo('password'),
    ])

app/dashboard/routes.py
from datetime import datetime

from flask import Blueprint, current_app, flash, redirect, \
                render_template, request, url_for
from flask_login import current_user, login_required

from app.common.decorators import check_confirmed
from app.common.mail import send_mail
from app.auth.models import User
from app.post.models import Post
from app.common.utils import encode_token, save_image
from .forms import WritePostForm
from .forms import EditProfileForm


bp = Blueprint('dashboard', __name__, template_folder='templates')

@bp.route('/dashboard')
@login_required
@check_confirmed
def dashboard():
    return render_template('dashboard.html')

@bp.route('/dashboard/edit-profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_profile():
    form = EditProfileForm(obj=current_user)
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data

            if form.profile_image.data:
                current_user.profile_image_name = save_image(
                    form.profile_image.data,
                    current_app.config['MEDIA_PROFILE_DIR']
                )
                current_user.profile_thumbnail = False

            if form.background_image.data:
                current_user.background_image_name = save_image(
                    form.background_image.data,
                    current_app.config['MEDIA_BACKGROUND_DIR']
                )

            if form.password.data != '':
                current_user.created_password(form.password.data)

            if current_user.email != form.email.data:
                current_user.confirmed = False
                flash('Usted a cambiado su dirección de email, \
                un email de verificación fue enviado.', 'warning')

                current_user.email= form.email.data

                token = encode_token(current_user.email)
                url = url_for('auth.confirm_email', token=token, _external=True)
                body = render_template('email_template/email.txt', url=url)
                html = render_template('email_template/email.html', url=url)
                send_mail(
                    'Por favor, confirme su email',
                    recipients=[current_user.email],
                    sender=current_app.config['MAIL_USERNAME'],
                    body=body,
                    html=html
                )

            flash('Perfil actualizado con exito', 'success')
            current_user.updated = datetime.now()
            current_user.save()
            return redirect(url_for('dashboard.dashboard'))

    return render_template('edit_profile.html', form=form)

@bp.route('/dashboard/write-post', methods=['GET', 'POST'])
@login_required
@check_confirmed
def write_post():
    form = WritePostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            title = form.title.data
            content = form.content.data
            read_time = form.read_time.data

            post = Post(
                title,
                content,
                read_time,
                current_user.id
            )

            post.save()
            return redirect(url_for(
                'post.show_post',
                uuid=post.public_id,
                slug=post.title_slug
            ))
    return render_template('write_post.html', form=form)

@bp.route('/dashboard/<string:uuid>/edit-post', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_post(uuid):
    post = Post.query.filter_by(public_id=uuid).first_or_404()

    form = WritePostForm(obj=post)
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            post.read_time = form.read_time.data

            if post.author_id == current_user.id:
                post.save()

        return redirect(url_for(
                'post.show_post',
                uuid=post.public_id,
                slug=post.title_slug
            ))

    return render_template('edit_post.html', form=form, post=post)

@bp.route('/dashboard/<string:uuid>/delete-post', methods=['GET', 'POST'])
@check_confirmed
@login_required
def delete_post(uuid):
    post = Post.query.filter_by(public_id=uuid).first_or_404()

    if post.author_id != current_user.id:
        return redirect(url_for('dashboard.dashboard'))

    if request.method == 'POST':
        post.delete()
        return redirect(url_for('dashboard.dashboard'))


    return render_template('delete_post.html', post=post)

@bp.route('/follow/<username>', methods=['POST'])
@login_required
@check_confirmed
def follow(username):
    if request.method == 'POST':
        user = User.query.filter_by(username=username).first_or_404()

        if user.id == current_user.id:
            return redirect(url_for('public.show_user', username=username))

        current_user.follow(user)
        current_user.save()
        return redirect(url_for('public.show_user', username=username))

@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
@check_confirmed
def unfollow(username):
    if request.method == 'POST':
        user = User.query.filter_by(username=username).first_or_404()

        if user.id == current_user.id:
            return redirect(url_for('public.show_user', username=username))

        current_user.unfollow(user)
        current_user.save()
        return redirect(url_for('public.show_user', username=username))

app/dashboard/templates/dashboard.html
{% extends '_base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="pt-2 mt-2 text-end">
    <p class="h3 text-muted">Bienvenid@, {{ current_user.first_name }} {{ current_user.last_name}}</p>
</div>

<div class="px-4 py-2 my-2 text-center">
    <h1 class="display-5 fw-bold">Dashboard</h1>
</div>

<p class="display-5">Mis Artículos:</p>

{% if current_user.posts != [] %}

<div class="accordion" id="accordionExample">
    {% for post in current_user.posts %}
    <div class="accordion-item">
        <h4 class="accordion-header" id="heading{{ post.id }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse{{ post.id }}" aria-expanded="false" aria-controls="collapse{{ post.id }}">
                {{ post.title}}
            </button>
        </h4>
        <div id="collapse{{ post.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ post.id }}"
            data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>{{ post.content[:100] }}...</p>
                <div>
                    <p>Ver <a href="{{ url_for('post.show_post',
                            uuid=post.public_id,
                            slug=post.title_slug) }}">
                            {{ post.title }}
                        </a></p>
                    <a href="{{ url_for('dashboard.edit_post', uuid=post.public_id) }}"><span
                        class="badge rounded-pill bg-primary">Editar</span></a>

                <a href="{{ url_for('dashboard.delete_post', uuid=post.public_id) }}"><span
                        class="badge rounded-pill bg-danger">Eliminar</span></a>
                        
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endif %}

{% endblock %}

app/dashboard/templates/delete_post.html
{% extends '_base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-6 fw-bold">Esta seguro de querer eliminar este articulo.</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Esta apunto de eliminar la publicación: {{ post.title}}, esta ación es irreversible y no podra deshacer los cambios una vez eliminada la publicación. Estas seguro de querer continuar?</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <form method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button class="btn btn-danger">Si, seguro</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/dashboard/templates/edit_post.html
{% extends '_base.html' %}

{% block title %}Edit Post{% endblock%}

{% block content %}
<div class="px-4 py-2 my-2 text-center">
    <h1 class="display-5 fw-bold">Editar Publicación</h1>
</div>

<div class="card mt-5">
    <div class="card-body">
        <form method="post" autocomplete="off">
            {% from '_formhelper.html' import render_field %}
            {{ form.csrf_token }}

            <div class="row">
                <div class="col-sm-9">
                    {{ render_field(form.title) }}
                </div>
                <div class="col-sm-3">
                    {{ render_field(form.read_time) }}
                </div>
            </div>
        
            {{ form.content.label }}
            {{ form.content }}
        
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
    {% if post.updated %}
    <div class="card-footer text-muted">
        Ultimo cambio {{current_user.updated|strftime('full')}}
    </div>
    {% endif %}
</div>

{{ ckeditor.load() }}
{{ ckeditor.config(name='content') }}

{% endblock%}

app/dashboard/templates/edit_profile.html
{% extends '_base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div class="px-4 py-2 my-2 text-center">
    <h1 class="display-5 fw-bold">Editar perfil</h1>
</div>

<div class="card my-5 auth-form">
    <div class="card-body">
        <form method="post" autocomplete="off" enctype="multipart/form-data">
            {% from '_formhelper.html' import render_field %}

            {{ form.csrf_token }}

            {{ render_field(form.username) }}

            {{ render_field(form.first_name) }}

            {{ render_field(form.last_name) }}

            {{ render_field(form.email) }}

            {{ render_field(form.profile_image) }}

            {{ render_field(form.background_image)}}

            {{ render_field(form.password) }}

            {{ render_field(form.confirm_password) }}

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>

    {% if current_user.updated %}
    <div class="card-footer text-muted">
        Ultimo cambio {{current_user.updated|strftime('full')}}
    </div>
    {% endif %}
</div>
{% endblock %}

app/dashboard/templates/write_post.html
{% extends '_base.html' %}

{% block title %}Write Post{% endblock%}

{% block content %}
<div class="px-4 py-2 my-2 text-center">
    <h1 class="display-5 fw-bold">Escribe tu publicación</h1>
</div>

<div class="card mt-5">
    <div class="card-body">
        <form method="post" autocomplete="off">
            {% from '_formhelper.html' import render_field %}
            {{ form.csrf_token }}

            <div class="row">
                <div class="col-sm-9">
                    {{ render_field(form.title) }}
                </div>
                <div class="col-sm-3">
                    {{ render_field(form.read_time) }}
                </div>
            </div>
        
            {{ form.content.label(class="form-label") }}
            {{ form.content }}
        
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
</div>

{{ ckeditor.load() }}
{{ ckeditor.config(name='content') }}

{% endblock%}