app/common/form/__init__.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField
from wtforms.validators import DataRequired, Email, Length

from .form_validators import *

class BaseUserForm(FlaskForm):
    """
    Formulario base para el SignupForm y el EditProfileForm
    """
    username = StringField('Username', validators=[
        DataRequired('Es necesario que rellene este campo'),
        Length(min=6, max=12),
        UsernameIsalnum(),
        IsUsernameBusy()
    ])
    first_name = StringField('First Name', validators=[
        Length(min=3, max=12),
        DataRequired('Es necesario que rellene este campo')
    ])
    last_name = StringField('Last Name', validators=[
        Length(min=3, max=12),
        DataRequired('Es necesario que rellene este campo'),
    ])
    email = StringField('Email', validators=[
        DataRequired('Es necesario que rellene este campo'),
        Email('La dirección de corre electrónico no es correcta'),
        IsEmailBusy()
    ])
    profile_image = FileField('imagen de perfil', validators=[
        FileAllowed(['jpg', 'png'], 'Solo se permiten imágenes')
    ])
    background_image = FileField('Imagen de fondo', validators=[
        FileAllowed(['jpg', 'png'], 'Solo se permiten imágenes')
    ])

app/dashboard/routes.py
from datetime import datetime

from flask import Blueprint, current_app, flash, redirect, \
                render_template, request, url_for
from flask_login import current_user, login_required

from app.common.decorators import check_confirmed
from app.common.mail import send_mail
from app.auth.models import User
from app.post.models import Post
from app.common.utils import encode_token, save_image
from .forms import WritePostForm
from .forms import EditProfileForm


bp = Blueprint('dashboard', __name__, template_folder='templates')

@bp.route('/dashboard')
@login_required
@check_confirmed
def dashboard():
    return render_template('dashboard.html')

@bp.route('/dashboard/edit-profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_profile():
    form = EditProfileForm(obj=current_user)
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data

            if form.profile_image.data:
                current_user.profile_image_name = save_image(
                    form.profile_image.data,
                    current_app.config['MEDIA_PROFILE_DIR']
                )
                current_user.profile_thumbnail = False

            if form.background_image.data:
                current_user.background_image_name = save_image(
                    form.background_image.data,
                    current_app.config['MEDIA_BACKGROUND_DIR']
                )

            if form.password.data != '':
                current_user.created_password(form.password.data)

            if current_user.email != form.email.data:
                current_user.confirmed = False
                flash('Usted a cambiado su dirección de email, \
                un email de verificación fue enviado.', 'warning')

                current_user.email= form.email.data

                token = encode_token(current_user.email)
                url = url_for('auth.confirm_email', token=token, _external=True)
                body = render_template('email_template/email.txt', url=url)
                html = render_template('email_template/email.html', url=url)
                send_mail(
                    'Por favor, confirme su email',
                    recipients=[current_user.email],
                    sender=current_app.config['MAIL_USERNAME'],
                    body=body,
                    html=html
                )

            flash('Perfil actualizado con exito', 'success')
            current_user.updated = datetime.now()
            current_user.save()
            return redirect(url_for('dashboard.dashboard'))

    return render_template('edit_profile.html', form=form)

@bp.route('/dashboard/write-post', methods=['GET', 'POST'])
@login_required
@check_confirmed
def write_post():
    form = WritePostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            title = form.title.data
            content = form.content.data
            read_time = form.read_time.data

            post = Post(
                title,
                content,
                read_time,
                current_user.id
            )

            post.save()
            return redirect(url_for(
                'post.show_post',
                uuid=post.public_id,
                slug=post.title_slug
            ))
    return render_template('write_post.html', form=form)

@bp.route('/dashboard/<string:uuid>/edit-post', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_post(uuid):
    post = Post.query.filter_by(public_id=uuid).first_or_404()

    form = WritePostForm(obj=post)
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            post.read_time = form.read_time.data

            if post.author_id == current_user.id:
                post.save()

        return redirect(url_for(
                'post.show_post',
                uuid=post.public_id,
                slug=post.title_slug
            ))

    return render_template('edit_post.html', form=form, post=post)

@bp.route('/dashboard/<string:uuid>/delete-post', methods=['GET', 'POST'])
@check_confirmed
@login_required
def delete_post(uuid):
    post = Post.query.filter_by(public_id=uuid).first_or_404()

    if post.author_id != current_user.id:
        return redirect(url_for('dashboard.dashboard'))

    if request.method == 'POST':
        post.delete()
        return redirect(url_for('dashboard.dashboard'))


    return render_template('delete_post.html', post=post)

@bp.route('/follow/<username>', methods=['POST'])
@login_required
@check_confirmed
def follow(username):
    if request.method == 'POST':
        user = User.query.filter_by(username=username).first_or_404()

        if user.id == current_user.id:
            return redirect(url_for('public.show_user', username=username))

        current_user.follow(user)
        current_user.save()
        return redirect(url_for('public.show_user', username=username))

@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
@check_confirmed
def unfollow(username):
    if request.method == 'POST':
        user = User.query.filter_by(username=username).first_or_404()

        if user.id == current_user.id:
            return redirect(url_for('public.show_user', username=username))

        current_user.unfollow(user)
        current_user.save()
        return redirect(url_for('public.show_user', username=username))

app/templates/401.html
{% extends '_errorbase.html'%}

{% block title %}401 Unauthorized{% endblock %}

{% block content %}
Upsss! lo sentimos pero usted no no tiene permisos suficientes para acceder.
{% endblock %}

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%} | Bienvenido al miniblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    {% block prism %}{% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('public.index') }}">MiniBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('dashboard.dashboard') }}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Opciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('dashboard.edit_profile')}}">Editar Perfil</a>
                            </li>
                            <li><a class="dropdown-item"
                                    href="{{ url_for('public.show_user', username=current_user.username)}}">Ver
                                    Perfil</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('dashboard.write_post')}}">Escribir Publicación</li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup')}}">Signup</a>
                    </li>
                    {% endif %}

                </ul>
                <form action="{{ url_for('public.search')}}" method="GET" class="d-flex">
                    <input class="form-control me-2" name="q" type="search" placeholder="Buscar Publicación"
                        aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}

        {% for category, message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show mt-2" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor%}
        {% endif%}
        {% endwith %}

        {% block content %}{% endblock%}
    </div>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
</body>

</html>

app/templates/_errorbase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>

<body style="background: #f5f5f5;">

    <div class="container">
        <div class="px-4 py-5 my-5 text-center">
            <h1 class="display-5 fw-bold">{{ statuscode }}</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">{% block content %}{% endblock %}</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a href="/" class="btn btn-outline-secondary btn-lg px-4">Volver a estar seguro!</a>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

app/templates/_formhelper.html
{% macro render_field_custom(field) %}
{{ field.label(class="label")|safe}}
{{ field(**kwargs)|safe }}
{% if field.errors %}
<ul class=errors>
  {% for error in field.errors %}
  <li>{{ error }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endmacro %}

{% macro render_field_login(field) %}
<div class="form-floating mb-3">
  {{ field(class="form-control", placeholder="username") }}
  {{ field.label }}
</div>
{% endmacro %}

{% macro render_field(field) %}
<div class="mb-3">
  {% if not field.errors %}

  {{ field.label(class="form-label") }}
  {{ field(class="form-control") }}

  {% else %}

  {{ field.label(class="form-label") }}
  {{ field(class="form-control is-invalid") }}

  {% for error in field.errors %}
  <div class="invalid-feedback">
    {{ error}}
  </div>
  {% endfor %}
  {% endif%}
</div>
{% endmacro %}

app/templates/_paginationhelper.html
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="pagination">
    <ul class="pagination pagination-lg flex-wrap">
        <li class="page-item
        {% if not pagination.has_prev %}
        disabled
        {% endif%}">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev_num) }}">Previous</a>
        </li>

        <li class="page-item
        {% if not pagination.has_next %}
        disabled
        {% endif%}">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.next_num) }}">Next</a>
        </li>
    </ul>
</nav>
{% endmacro %}